# Generated by Django 4.1.3 on 2022-12-03 19:37

from django.db import migrations, models
import taxi.models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0003_alter_driver_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="default.png",
                null=True,
                upload_to=taxi.models.photo_path,
            ),
        ),
    ]
